USE CUSTOMER;
CREATE TABLE EMPLOYEES (EMPLOYEE_ID INT PRIMARY KEY IDENTITY(1,1) , NAME VARCHAR(30) , AGE INT , DEPARTMENT VARCHAR(50) , SALARY DECIMAL(10 , 2));
INSERT INTO EMPLOYEES VALUES( 'SATISH' , 23 , 'AI' , 25000.00) ,( 'HARI' , 20 , 'DS' , 20000.00),( 'HARIKA' , 22 , 'ECE' , 30000.00);
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES 
SET DEPARTMENT='IT' WHERE DEPARTMENT ='AI';
UPDATE EMPLOYEES 
SET DEPARTMENT='HR' WHERE DEPARTMENT ='DS';

UPDATE EMPLOYEES 
SET SALARY =(SALARY*1.10) WHERE DEPARTMENT='HR';

DELETE EMPLOYEES
WHERE DEPARTMENT='IT';

INSERT INTO EMPLOYEES VALUES('BUNNY' , 24, 'CSE' , 40000.00)
;

UPDATE EMPLOYEES
SET SALARY=70000.00 WHERE NAME='HARI';

UPDATE EMPLOYEES 
SET DEPARTMENT='SENIOR STAFF' WHERE SALARY>50000.00;

SELECT * FROM EMPLOYEES;


DELETE EMPLOYEES
WHERE AGE > 60;

SELECT NAME , SALARY FROM EMPLOYEES;

SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT='HR'  AND SALARY >50000.00; 

SELECT SALARY FROM EMPLOYEES
ORDER  BY SALARY DESC;



SELECT * FROM EMPLOYEES  
WHERE AGE > 30;

SELECT DEPARTMENT FROM EMPLOYEES WHERE DEPARTMENT
IN ('HR' , 'FINANACE');



SELECT * FROM EMPLOYEES  
WHERE SALARY BETWEEN 30000 AND 60000;

SELECT * FROM EMPLOYEES  
WHERE NAME LIKE 'A%';

SELECT * FROM EMPLOYEES  
WHERE DEPARTMENT <> 'IT';


SELECT * FROM EMPLOYEES  
WHERE DEPARTMENT IN ('Sales', 'Marketing');

SELECT DISTINCT DEPARTMENT FROM EMPLOYEES;
SELECT EMPLOYEE_ID AS ID, NAME, SALARY AS "Monthly Income"  
FROM EMPLOYEES;


SELECT *  
FROM EMPLOYEES  
WHERE NAME LIKE '%John%'  
AND SALARY > 40000;




